# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [4]:
import numpy as np
arr=np.arange(10).reshape(2,5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [8]:
arr=np.arange(10).reshape(2,5)
arr2=np.ones(10).reshape(2,5)
arrV=np.vstack((arr,arr2))
arrV=arrV.astype(int)
arrV

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [9]:
arr=np.arange(10).reshape(2,5)
arr2=np.ones(10).reshape(2,5)
arrH=np.hstack((arr,arr2))
arrH=arrH.astype(int)
arrH

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [14]:
arr=np.array([[0,1],[2,3],[4,5],[6,7],[8,9]])
arrf=arr.flatten()
arrf

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [20]:
arr=np.arange(15).reshape(3,5,1) #3d
print("Original 3D array\n",arr)
arr1d=np.ravel(arr)
print("desired output")
arr1d   #1d

Original 3D array
 [[[ 0]
  [ 1]
  [ 2]
  [ 3]
  [ 4]]

 [[ 5]
  [ 6]
  [ 7]
  [ 8]
  [ 9]]

 [[10]
  [11]
  [12]
  [13]
  [14]]]
desired output


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [23]:
arr=np.arange(15) #3d
print("Original 1D array\n",arr)
arr3d=arr.reshape(3,5,1)
print("desired output in 3D (higher dimension)")
arr3d

Original 1D array
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
desired output in 3D (higher dimension)


array([[[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4]],

       [[ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12],
        [13],
        [14]]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [26]:
arr=np.arange(1,26).reshape(5,5)
arrS=np.square(arr)
arrS

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100],
       [121, 144, 169, 196, 225],
       [256, 289, 324, 361, 400],
       [441, 484, 529, 576, 625]], dtype=int32)

## Question:8

### Create 5x6 an array and find the mean?

In [27]:
arr=np.arange(1,31).reshape(5,6)
print(arr)
arr_mean=np.mean(arr)
print("Mean of Array is ",arr_mean)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]
Mean of Array is  15.5


## Question:9

### Find the standard deviation of the previous array in Q8?

In [28]:
print(arr)
arr_std=np.std(arr)
print("Standard Deviation of Array is ",arr_std)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]
Standard Deviation of Array is  8.65544144839919


## Question:10

### Find the median of the previous array in Q8?

In [29]:
print(arr)
arr_median=np.median(arr)
print("Median of Array is ",arr_median)


[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]
Median of Array is  15.5


## Question:11

### Find the transpose of the previous array in Q8?

In [32]:
print(arr)
arrT=arr.T
print("Transpose of above array is \n",arrT)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]
Transpose of above array is 
 [[ 1  7 13 19 25]
 [ 2  8 14 20 26]
 [ 3  9 15 21 27]
 [ 4 10 16 22 28]
 [ 5 11 17 23 29]
 [ 6 12 18 24 30]]


## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [39]:
arr=np.arange(16).reshape(4,4)
print("Our Array\n",arr)
arrd=np.diag(arr)
print("diagnol elements\n",arrd)
sumd=arrd.sum()
print("sum of diagnol elements\n",sumd)




Our Array
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
diagnol elements
 [ 0  5 10 15]
sum of diagnol elements
 30


## Question:13

### Find the determinant of the previous array in Q12?

In [44]:
from numpy.linalg import det
arr=np.arange(16).reshape(4,4)
print("Our Array\n",arr)
det_arr=det(arr)
print("Determinant of  Array\n",det_arr)  #zero it is here in this array

Our Array
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Determinant of  Array
 -2.9582283945787796e-30


## Question:14

### Find the 5th and 95th percentile of an array?

In [46]:
arr=np.arange(16).reshape(4,4)
print("Our Array\n",arr)
perc_5th=np.percentile(arr,5)
print("5th percentile of Array\n",perc_5th)
perc_95th=np.percentile(arr,95)
print("95th percentile of Array\n",perc_95th)


Our Array
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
5th percentile of Array
 0.75
95th percentile of Array
 14.25


## Question:15

### How to find if a given array has any null values?

In [50]:
arr=np.arange(1,17).reshape(4,4)
print("Our Array\n",arr)
(arr==0).any()

Our Array
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


False